# Generated by Django 3.1.3 on 2020-11-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201122_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='imageBook',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
