# Generated by Django 3.1.3 on 2020-11-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201122_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
