# Generated by Django 3.1.3 on 2020-12-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201124_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
