# Generated by Django 3.1.3 on 2020-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='detail',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ImageField(choices=[(0, 'Đang ra'), (1, 'Đã hoàn thành'), (2, 'Tạm ngưng')], default=0, upload_to=''),
        ),
    ]
