# Generated by Django 3.1.3 on 2020-12-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201213_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Đang ra'), (1, 'Đã hoàn thành'), (2, 'Tạm ngưng')], default=0),
        ),
    ]
